name: Update TFJob and Deploy

on:
 push:
   branches:
    - master

jobs:
  Rasa_Training_Deployment:
    runs-on: ubuntu-latest

    steps:
      # Install kubectl 
      - name: Install kubectl
        run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl               
        # uses: azure/setup-kubectl@v3
        # with:
        #   version: 'v1.30.1'
      - run: kubectl version --client
      - run: kubectl version --short
      
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Deploy to Kubernetes         
      - name: Deploy to Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f rasa_trainer.yaml
