name: Update TFJob and Deploy

on:
  push:
    branches: 
        ${GITHUB_REF#refs/heads/}

jobs:
  Rasa_Traning_Deployment:
    runs-on: ubuntu-latest

    steps:
     
      # Install kubectl 
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - run: kubectl version --client

      - name: Checkout repository
        uses: actions/checkout@v3
         
      # Deploy to KUbernetes         
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f rasa_trainer.yaml
