name: Conditional Workflow
on:
  create:
  push:
    paths:
      - 'rasa_trainer.yaml'
jobs:
  handle-create:
    if: github.event_name == 'create'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Perform actions on create
        run: echo "This is triggered by a create event."

  handle-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Perform actions on push
        run: echo "This is triggered by a push event."
