name: Update TFJob and Deploy

on:
 push:
   branches:
    - master

jobs:
  Rasa_Training_Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      # - uses: ThomasKliszowski/setup-kubectl@v1
      #   with:
      #     kube-config: ${{ secrets.KUBE_CONFIG }}
      #     kube-version: 1.20.15
          
      # Install kubectl 
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
           version: latest
           
      # - run: kubectl version
    
      # Deploy to Kubernetes         
      - name: Deploy to Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f rasa_trainer.yaml
